apiVersion: v1
kind: Service
metadata:
  name: service-for-application
spec:
  selector:
    app: rails-app
  type: ClusterIP
  ports:
    - name: port
      protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-for-application
spec:
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
      - name: rails-app
        image: takapon564/rest-web
        imagePullPolicy: Always
        command: ["bundle", "exec", "rails", "s"]
        envFrom:
        - configMapRef:
            name: rails-config
        ports:
        - containerPort: 3000