apiVersion: batch/v1
kind: Job
metadata:
  name: migration
  labels:
    app.kubernetes.io/name: rest-web
    app.kubernetes.io/instance: rest-web-db
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: dev
    app.kubernetes.io/managed-by: manual
spec:
  template:
    metadata:
      name: migration
    spec:
      containers:
      - name: migration
        image: takapon564/rest-web
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "./bin/rails db:create && ./bin/rails db:migrate"]
        envFrom:
        - configMapRef:
            name: app-config
      restartPolicy: Never